# permissions for end users to view remotedatanodes.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: remotedatanodes-viewer-role
rules:
- apiGroups:
  - cluster.ytsaurus.tech
  resources:
  - remotedatanodes
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - cluster.ytsaurus.tech
  resources:
  - remotedatanodes/status
  verbs:
  - get
