# permissions for end users to view spyts.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: spyt-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: ytsaurus-k8s-operator
    app.kubernetes.io/part-of: ytsaurus-k8s-operator
    app.kubernetes.io/managed-by: kustomize
  name: spyt-viewer-role
rules:
- apiGroups:
  - cluster.ytsaurus.tech
  resources:
  - spyts
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - cluster.ytsaurus.tech
  resources:
  - spyts/status
  verbs:
  - get
