apiVersion: cluster.ytsaurus.tech/v1
kind: Spyt
metadata:
  labels:
    app.kubernetes.io/name: spyt
    app.kubernetes.io/instance: spyt-sample
    app.kubernetes.io/part-of: ytsaurus-k8s-operator
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: ytsaurus-k8s-operator
  name: myspyt
spec:
  ytsaurus:
    name:
      minisaurus
  image: ghcr.io/ytsaurus/spyt:1.78.0
